---
- name: Test Environment Provisioning
  hosts: test_environments
  remote_user: fedora
  become: true
  gather_facts: false

  tasks:
  
  - name: Wait until the instance is ready
    ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 60
  
  - name: Gather facts for first time
    ansible.builtin.setup:

  - name: Required Packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items:
      - podman
      - cuda-toolkit
      - python3
      - git
      - python3-pip
      - cmake
      - build-essential
      - virtualenv
      - make
    
  # - name: Install bootc
  #   ansible.builtin.command: |
  #     sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-d9fbb93c29
  
  # - name: Install bootc
  #   ansible.builtin.command: make -C /opt/bootc install

  # - name: Run Instructlab image
  #   containers.podman.podman_container:
  #     name: {{ image_name }}
  #     image: ghcr.io/containers/{{ image_name }}:latest
  #     state: started
  #     interactive: true
  #     tty: true
  #     detach: false
  #   vars:
  #     my_variable: "{{ lookup('env', 'image_name') }}"