---
- name: Test Environment Provisioning
  hosts: test_environments
  remote_user: fedora
  become: true
  gather_facts: false

  tasks:
  
  - name: Wait until the instance is ready
    ansible.builtin.wait_for_connection:
    delay: 15
    timeout: 180
  
  - name: Gather facts for first time
    ansible.builtin.setup:

  - name: Required Packages
    ansible.builtin.package:
      name: podman
      state: present
