apiVersion: v1
kind: Pod
metadata:
  labels:
    app: summarizer
  name: summarizer
spec:
  initContainers:
  - name: model-file
    image: MODELIMAGE
    command: ['/usr/bin/install', "/model/model.file", "/shared/"]
    volumeMounts:
    - name: model-file
      mountPath: /shared
  containers:
  - env:
    - name: MODEL_SERVICE_ENDPOINT
      value: http://0.0.0.0:8001/v1
    image: APPIMAGE
    name: summarizer-inference
    ports:
    - containerPort: 8501
      hostPort: 8501
    securityContext:
      runAsNonRoot: true
  - env:
    - name: HOST
      value: 0.0.0.0
    - name: PORT
      value: 8001
    - name: MODEL_PATH
      value: /model/model.file
    image: SERVERIMAGE
    name: summarizer-model-service
    ports:
    - containerPort: 8001
      hostPort: 8001
    securityContext:
      runAsNonRoot: true
    volumeMounts:
    - name: model-file
      mountPath: /model
  volumes:
  - name: model-file
    emptyDir: {}
