name: Update quay.io/ai-lab images

on:
  schedule: # schedule the job to run at 12 AM daily
   - cron: '0 0 * * *'
  
  workflow_dispatch:

env:
  REGISTRY: quay.io/ai-lab
  CHATBOT_IMAGE_NAME: chatbot
  LLAMACPP_PYTHON_IMAGE_NAME: llamacpp-python
  CHROMADB_IMAGE_NAME: chromadb
  RAG_IMAGE_NAME: rag

jobs:
  build-and-push-rag-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v4.1.1
      # required for multi-arch builds
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build rag
        id: build_rag
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.RAG_IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          containerfiles: ./recipes/natural_language_processing/rag/builds/Containerfile
          context: recipes/natural_language_processing/rag

      - name: Login to quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push rag image
        id: push_rag
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build_rag.outputs.image }}
          tags: ${{ steps.build_rag.outputs.tags }}

  build-and-push-chromadb-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4.1.1
      # required for multi-arch builds
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build chromadb
        id: build_chromadb
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.CHROMADB_IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          context: vector_dbs/chromadb
          containerfiles: ./vector_dbs/chromadb/Containerfile

      - name: Login to quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push chromadb image
        id: push_chromadb
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build_chromadb.outputs.image }}
          tags: ${{ steps.build_chromadb.outputs.tags }}

  build-and-push-chatbot-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4.1.1

      # required for multi-arch builds
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build chatbot image
        id: build_chatbot_image
        uses: redhat-actions/buildah-build@v2.13
        with:
          image: ${{ env.CHATBOT_IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          containerfiles: ./recipes/natural_language_processing/chatbot/builds/Containerfile
          context: recipes/natural_language_processing/chatbot

      - name: Login to quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push chatbot image
        id: push_chatbot_image
        uses: redhat-actions/push-to-registry@v2.8
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build_chatbot_image.outputs.image }}
          tags: ${{ steps.build_chatbot_image.outputs.tags }}
