name: chatbot

on:
  pull_request:
    branches:
      - main
    # paths:
    #   - ./recipes/natural_language_processing/chatbot/**
    #   - .github/workflows/chatbot.yaml
  push:
    branches:
      - main
    # paths:
    #   - ./recipes/natural_language_processing/chatbot/**
    #   - .github/workflows/chatbot.yaml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/chatbot

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    services:
      registry:
        image: registry:2.8.3
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Login to ghcr
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2.13
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest
          containerfiles: ./recipes/natural_language_processing/chatbot/builds/Containerfile
          context: recipes/natural_language_processing/chatbot

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./recipes/natural_language_processing/chatbot
        run: make install

      - name: Run tests
        working-directory: ./recipes/natural_language_processing/chatbot
        run: make test

