name: dummy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dummy:
    if: "github.repository == 'containers-mirror/ai-lab-recipes'"
    runs-on: ubuntu-22.04-2core
    steps:
      - name: hello world
        run: |
          echo "hello world!"
   