name: Model Servers

on:
  pull_request:
    branches:
      - main
    paths:
      - ./model_servers/
      - .github/workflows/model_servers.yaml
  push:
    branches:
      - main
    paths:
      - ./model_servers/
      - .github/workflows/model_servers.yaml

  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    strategy:
      matrix:
        include:
          - image_name: llamacpp_python
            model: mistral
            flavor: base
          - image_name: llamacpp_python_vulkan
            model: mistral
            flavor: vulkan
          - image_name: llamacpp_python_cuda
            model: mistral
            flavor: cuda
          - image_name: whispercpp
            model: whisper-small
            flavor: base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    services:
      registry:
        image: registry:2.8.3
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
      
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2.13
        with:
          image: ${{ env.REGISTRY }}/${{ github.repository_owner}}/${{ matrix.image_name }}
          platforms: linux/amd64, linux/arm64
          tags: latest
          containerfiles: ./model_servers/${{ matrix.image_name }}/${{ matrix.flavor }}/Containerfile
          context: model_servers/${{ matrix.image_name }}/

      - name: Download model
        working-directory: ./model_servers/${{ matrix.image_name }}/
        run: make ${{ matrix.model }}

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'

      - name: Install python dependencies
        working-directory: ./model_servers/${{ matrix.image_name }}/
        run: make install

      - name: Run tests
        working-directory: ./model_servers/${{ matrix.image_name }}/
        run: make test
        env:
          IMAGE_NAME: ${{ matrix.image_name }}

      - name: Login to Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: redhat-actions/podman-login@v1.7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        id: push_image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: redhat-actions/push-to-registry@v2.8
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
