name: model_servers

on:
  pull_request:
    branches:
      - main
    paths:
      - ./model_servers/llamacpp_python/**
      - .github/workflows/model_servers.yaml
  push:
    branches:
      - main
    paths:
      - ./model_servers/llamacpp_python/**
      - .github/workflows/model_servers.yaml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/model_servers

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    services:
      registry:
        image: registry:2.8.3
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Login to ghcr
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2.13
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest
          containerfiles: ./model_servers/llamacpp_python/base/Containerfile
          context: model_servers/llamacpp_python/

      - name: Download model
        working-directory: ./model_servers/llamacpp_python/
        run: make mistral-7b-instruct-v0.1.Q4_K_M.gguf

      - name: Set up Python
        uses: actions/setup-python@v5.0.0

      - name: Install python dependencies
        working-directory: ./model_servers/llamacpp_python/
        run: make install

      - name: Run tests
        working-directory: ./model_servers/llamacpp_python/
        run: make test
